### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'Models/MathRecog.pth'

### ISSUE THREAD

**Issue by AaaJrwp4** [omarWafaay/MathFormApp#3]
Hello! When starting your app I get the following error:

```
2022-05-09 14:40:14.264 Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/streamlit/script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
  File "/Users/.../MathFormApp/app.py", line 35, in <module>
    mathargs, *mathobjs = RM.initialize()
  File "/Users/.../MathFormApp/Recog_MathForm.py", line 142, in initialize
    model.load_state_dict(torch.load(args.checkpoint, map_location=args.device),strict=False)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'Models/MathRecog.pth'
```
It looks like the ```Models``` directory is missing the ```MathRecog.pth``` file. Can you help me out on this issue ?

**Comment by SunYue98** [comment]
I have the same problem, have you found the missing file?

**Comment by AaaJrwp4** [comment]
Hey @GulpFire ! Yes I solved it. Take a look at "MathFormApp/app.py" line 23. There you can see the google drive link. I think I donwloaded it with that link.

**Comment by YingZhuY** [comment]
It works for me, thx. Just restore the commented out code of these lines.
